src/WebUi/Models/DeviceViewModel.cs
using System;
using EDeviceClaims.Domain.Models;
using System.Linq;

namespace EDeviceClaims.WebUi.Models
{
    public class DeviceViewModel
    {
        public DeviceViewModel(PolicyWithClaimsDomainModel policy)
        {
            PolicyId = policy.Id;
            PolicyNumber = policy.Number;
            SerialNumber = policy.SerialNumber;
            Name = policy.DeviceName;
            WhenCreated = policy.WhenCreated;
            WhenLastUpdated = policy.WhenLastUpdated;
            MostCurrentClaim = (policy.Claims.Any()) ? new ClaimViewModel(policy.Claims.First()) : null;
        }

        public string Name { get; set; }

        public string SerialNumber { get; set; }

        public string PolicyNumber { get; set; }

        public Guid PolicyId { get; set; }

        public ClaimViewModel MostCurrentClaim { get; set; }

        public DateTime WhenCreated { get; set; }
        public DateTime? WhenLastUpdated { get; set; }

        public bool ShowViewClaimButton()
        {
            return MostCurrentClaim != null;
        }
    }
}

src/WebUi/Areas/Underwriter/Controllers/DeviceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EDeviceClaims.Core;
using EDeviceClaims.Domain.Services;
using EDeviceClaims.WebUi.Controllers;

namespace EDeviceClaims.WebUi.Area.Underwriter.Controllers
{

    

    [Authorize(Roles = ApplicationRoles.Underwriter)]
    public class UnderwriterAppController : AppController
    {
        
    }

}

src/WebUi/Controllers/ClaimController.cs
using EDeviceClaims.Domain.Services;
using EDeviceClaims.WebUi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EDeviceClaims.Core;
using EDeviceClaims.Domain.Models;

namespace EDeviceClaims.WebUi.Controllers
{
    [Authorize(Roles = ApplicationRoles.PolicyHolder)]
    public class ClaimController : AppController
    {
        //private IPolicyService _policyService = new PolicyService();
        private IClaimsService _claimsService = new ClaimsService();
        // GET: Claims 
        

        public ActionResult Start(Guid id)
        {
            var claimDomainModel = _claimsService.StartClaim(id);
            var model = new ClaimViewModel(claimDomainModel);

            return View("Edit",model);
        }

        public ActionResult Edit(Guid id)
        {
            var claimDomainModel =  _claimsService.GetById(id);
            var model = new ClaimViewModel(claimDomainModel);
            return View(model);
        }
        
        public ActionResult Details(Guid id)
        {
            return null;
        }
    }
}

src/WebUi/Controllers/ClaimsController.cs
using EDeviceClaims.Domain.Services;
using EDeviceClaims.WebUi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EDeviceClaims.Core;
using EDeviceClaims.Domain.Models;

namespace EDeviceClaims.WebUi.Controllers
{
    [Authorize(Roles = ApplicationRoles.PolicyHolder)]
    public class ClaimsController : AppController
    {
        //private IPolicyService _policyService = new PolicyService();
        private IClaimsService _claimsService = new ClaimsService();
        // GET: Claims 
        

        public ActionResult Start(Guid id)
        {
            var claimDomainModel = _claimsService.StartClaim(id);
            var model = new ClaimViewModel(claimDomainModel);

            return View(model);
        }

        public ActionResult Edit(Guid id)
        {
            var claimDomainModel =  _claimsService.GetById(id);
            var model = new ClaimViewModel(claimDomainModel);
            return View(model);
        }
        
        public ActionResult Details(Guid id)
        {
            return null;
        }
    }
}

src/WebUi/Controllers/DeviceController.cs
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EDeviceClaims.Domain.Services;
using EDeviceClaims.WebUi.Models;
using System;
using EDeviceClaims.Core;

namespace EDeviceClaims.WebUi.Controllers
{
    [Authorize(Roles = ApplicationRoles.PolicyHolder)]
    public class DeviceController : AppController
    {
        private IPolicyService _policyService = new PolicyService();

        public ActionResult Index()
        {
            var domainModel = _policyService.GetByUserId(CurrentUserId);
            var model = new DeviceListViewModel(domainModel);

            return View(model);
        }

        public ActionResult Details(Guid id)
        {
            var domainModel = _policyService.GetById(id);
            var model = new DeviceViewModel(domainModel);
            return View(model);
        }
    }
}

src/WebUi/Views/Device/Details.cshtml
@model EDeviceClaims.WebUi.Models.DeviceViewModel

@{
    ViewBag.Title = "Device Details";
}

<div class="row">
    <div class="col-md-12">
        <h2>File a Claim</h2>


        <div class="col-md-12" style="margin-bottom:20px">
            <div class="col-md-4">
                @if (Model.Name == "iPhone 6+")
                {
                    <img src="https://sc01.alicdn.com/kf/HTB1dBcZFFXXXXcAXpXXq6xXFXXX4/200855197/HTB1dBcZFFXXXXcAXpXXq6xXFXXX4.jpg" width="350" alt="IPhone" />
                }
                @if (Model.Name == "Android")
                {
                    <img src="https://cdn.shopify.com/s/files/1/0808/0067/products/s7_edge_rugged_armor_title_f2701768-857d-4bb2-99d1-ceb484b5a017_large.jpg?v=1456440500" width="350" alt="Android" />
                }
                @if (Model.Name == "Windows")
                {
                    <img src="http://imagescdn.tweaktown.com/news/4/8/48962_034_microsoft-updates-windows-device-recovery-lumia-550-950-xl_full.jpg" width="350" alt="Windows Lumia" />
                }
                @if (Model.Name == "Null")
                {
                    <img src="http://intraweb.stockton.edu/eyos/sobl/content/images/msw%20faculty/noimage.gif" width="350" alt="no image" />
                }

            </div>
            <div class="col-md-6" style="margin-top: 20px">
                <ul style="list-style:none;">

                    <li>Product: @Model.Name</li>
                    <li>Serial Number: @Model.SerialNumber</li>
                    <li>Policy Number: @Model.PolicyNumber</li>
                    <li>Purchase Date: @Model.WhenCreated</li>
                    <!-- include only if a claim has been filed-->
                    @if (@Model.ShowViewClaimButton())
                    {
                        <li>Last Updated: @Model.WhenLastUpdated</li>
                    }
                    
                    <!--end include only if a claim has been filed-->
                </ul>
            </div>
            <div class="col-md-2" style="margin-top:200px">
                
                @if (Model.ShowViewClaimButton())
                {
                    @Html.ActionLink("Check Claim Status", "Details", "Claims", routeValues: new { id = Model.PolicyId }, htmlAttributes: new { @class = "btn btn-warning btn-sm" })
                }
                else
                {
                    @Html.ActionLink("Submit a Claim", "Start", "Claims", routeValues: new { id = Model.PolicyId }, htmlAttributes: new { @class = "btn btn-danger btn-sm" })
                }

            </div>

        </div>



        <!--<p><a class="btn btn-default" href="/Home/Index">File A Claim &raquo;</a></p>-->
    </div>
</div>

src/WebUi/Views/Device/GetClaimButton.cshtml
@model EDeviceClaims.WebUi.Models.DeviceViewModel

@if (Model.ShowViewClaimButton())
{
    @Html.ActionLink("View Claim", "Edit", "Claim", routeValues: new { id = Model.MostCurrentClaim.Id }, htmlAttributes: new { @class = "btn btn-warning btn-sm" })
}
else
{
    @Html.ActionLink("Submit a Claim", "Start", "Claim", routeValues: new { id = Model.PolicyId }, htmlAttributes: new { @class = "btn btn-danger btn-sm" })
}

src/WebUi/Views/Device/Index.cshtml
@model EDeviceClaims.WebUi.Models.DeviceListViewModel
@{
    ViewBag.Title = "New Claim";
}
<div class="row">
    <div class="col-md-12">
        <h2>Manage My Devices</h2>

        @foreach (var thing in Model)
            {
            <div class="row">
                <div class="col-md-12" style="margin-bottom:20px">
                    <div class="col-md-4">
                        @if (thing.Name == "iPhone 6+")
                        {
                            <img src="https://sc01.alicdn.com/kf/HTB1dBcZFFXXXXcAXpXXq6xXFXXX4/200855197/HTB1dBcZFFXXXXcAXpXXq6xXFXXX4.jpg" width="250" alt="IPhone" />
                        }
                        @if (thing.Name == "Android")
                        {
                            <img src="https://cdn.shopify.com/s/files/1/0808/0067/products/s7_edge_rugged_armor_title_f2701768-857d-4bb2-99d1-ceb484b5a017_large.jpg?v=1456440500" width="250" alt="Android" />
                        }
                        @if (thing.Name == "Windows")
                        {
                            <img src="http://imagescdn.tweaktown.com/news/4/8/48962_034_microsoft-updates-windows-device-recovery-lumia-550-950-xl_full.jpg" width="350" alt="Windows Lumia" />
                        }
                        @if (thing.Name == "Null")
                        {
                            <img src="http://intraweb.stockton.edu/eyos/sobl/content/images/msw%20faculty/noimage.gif" width="250" alt="no image" />
                        }

                    </div>
                    <div class="col-md-6" style="margin-top: 20px">
                        <ul style="list-style:none;">

                            @*<li>Product: Model.Name</li>*@
                            <li>Serial Number: @thing.SerialNumber</li>
                            <li>Policy Number: @thing.PolicyNumber</li>
                            <li>Purchase Date: @thing.WhenCreated</li>
                            @if (thing.ShowViewClaimButton())
                            {
                                if (thing.WhenLastUpdated == null)
                                {
                                    <li>Last Updated: @thing.WhenCreated </li>

                                }
                                else
                                {
                                    <li>Last Updated: @thing.WhenLastUpdated </li>

                                }
                            }
                            @*<li>@thing.MostCurrentClaim.Status</li>*@
                        </ul>
                    </div>
                    <div class="col-md-2" style="margin-top:200px">
                        @Html.Partial("GetClaimButton", thing)
                        @*@if (thing.HasPendingClaim)
                            {
                                @Html.ActionLink("Check Claim Status", "Details", "Claims",  new { id = thing.PolicyId },  new { @class = "btn btn-warning btn-sm" })
                            }
                            else
                            {
                                @Html.ActionLink("Submit a Claim", "NewClaim", "Claims", new { id = thing.PolicyId },  new { @class = "btn btn-danger btn-sm" })
                            }*@
                        @*@Html.ActionLink("Details", "Details", "Device", new { id = thing.PolicyId }, new { @class = "btn btn-danger btn-sm" })*@
                    </div>

                </div>
            </div>
        }

        <!--<p><a class="btn btn-default" href="/Home/Index">File A Claim &raquo;</a></p>-->
    </div>
</div>